Controllers/BeneficiariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GAP.InsuranceTest.Core.Entities;
using GAP.InsuranceTest.Data;
using GAP.InsuranceTest.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace GAP.InsuranceTest.Controllers
{
    [Authorize(Roles = "Administrator,Employee")]
    public class BeneficiariesController : Controller
    {
        private readonly IUnitOfWork _repository;

        public BeneficiariesController(IUnitOfWork repository)
        {
            _repository = repository;
        }

        // GET: Beneficiaries
        public async Task<IActionResult> Index()
        {
            return View(_repository.Beneficiaries.Get());
        }

        // GET: Beneficiaries/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beneficiary = _repository.Beneficiaries.GetByID(id);
            if (beneficiary == null)
            {
                return NotFound();
            }

            return View(beneficiary);
        }

        // GET: Beneficiaries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beneficiaries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,id_number,full_name,birth_date")] Beneficiary beneficiary)
        {
            if (ModelState.IsValid)
            {
                beneficiary.id = Guid.NewGuid();
                _repository.Beneficiaries.Insert(beneficiary);
                _repository.Commit();
                return RedirectToAction(nameof(Index));
            }
            return View(beneficiary);
        }

        // GET: Beneficiaries/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beneficiary = _repository.Beneficiaries.GetByID(id);
            if (beneficiary == null)
            {
                return NotFound();
            }
            return View(beneficiary);
        }

        // POST: Beneficiaries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("id,id_number,full_name,birth_date")] Beneficiary beneficiary)
        {
            if (id != beneficiary.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repository.Beneficiaries.Update(beneficiary);
                    _repository.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeneficiaryExists(beneficiary.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(beneficiary);
        }

        // GET: Beneficiaries/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beneficiary = _repository.Beneficiaries.GetByID(id);
            if (beneficiary == null)
            {
                return NotFound();
            }

            return View(beneficiary);
        }

        // POST: Beneficiaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var beneficiary = _repository.Beneficiaries.GetByID(id);
            _repository.Beneficiaries.Delete(beneficiary);
            _repository.Commit();
            return RedirectToAction(nameof(Index));
        }

        private bool BeneficiaryExists(Guid id)
        {
            return _repository.Beneficiaries.GetByID(id) != null;
        }
    }
}

Controllers/BeneficiaryInsurancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GAP.InsuranceTest.Core.Entities;
using GAP.InsuranceTest.Data;
using GAP.InsuranceTest.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace GAP.InsuranceTest.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class BeneficiaryInsurancesController : Controller
    {
        private readonly IUnitOfWork _repository;

        public BeneficiaryInsurancesController(IUnitOfWork repository)
        {
            _repository = repository;
        }

        // GET: BeneficiaryInsurances
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _repository.BeneficiaryInsurances.Get(null, null, "beneficiary,insurance");
            return View(applicationDbContext);
        }

        // GET: BeneficiaryInsurances/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beneficiaryInsurance = _repository.BeneficiaryInsurances.Get(x => x.beneficiaryId == id, null, "beneficiary,insurance").FirstOrDefault();
            if (beneficiaryInsurance == null)
            {
                return NotFound();
            }

            return View(beneficiaryInsurance);
        }

        // GET: BeneficiaryInsurances/Create
        public IActionResult Create()
        {
            ViewData["beneficiaryId"] = new SelectList(_repository.Beneficiaries.Get(), "id", "full_name");
            ViewData["insuranceId"] = new SelectList(_repository.Insurances.Get(), "id", "name");
            return View();
        }

        // POST: BeneficiaryInsurances/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("insuranceId,beneficiaryId")] BeneficiaryInsurance beneficiaryInsurance)
        {
            if (ModelState.IsValid)
            {
                //beneficiaryInsurance.beneficiaryId = Guid.NewGuid();
                _repository.BeneficiaryInsurances.Insert(beneficiaryInsurance);
                _repository.Commit();
                return RedirectToAction(nameof(Index));
            }
            ViewData["beneficiaryId"] = new SelectList(_repository.Beneficiaries.Get(), "id", "full_name");
            ViewData["insuranceId"] = new SelectList(_repository.Insurances.Get(), "id", "name");
            return View(beneficiaryInsurance);
        }


        // GET: BeneficiaryInsurances/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beneficiaryInsurance = _repository.BeneficiaryInsurances.Get(x => x.beneficiaryId == id, null, "beneficiary,insurance").FirstOrDefault();
            if (beneficiaryInsurance == null)
            {
                return NotFound();
            }

            return View(beneficiaryInsurance);
        }

        // POST: BeneficiaryInsurances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var beneficiaryInsurance = _repository.BeneficiaryInsurances.GetByID(id);
            _repository.BeneficiaryInsurances.Delete(beneficiaryInsurance);
            _repository.Commit();
            return RedirectToAction(nameof(Index));
        }

     
    }
}

Views/Beneficiaries/Create.cshtml
@model GAP.InsuranceTest.Core.Entities.Beneficiary

@{
    ViewData["Title"] = "Crear";
}

<h1>Nuevo Beneficiario</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id_number" class="control-label"></label>
                <input asp-for="id_number" class="form-control" type="number" />
                <span asp-validation-for="id_number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="full_name" class="control-label"></label>
                <input asp-for="full_name" class="form-control" />
                <span asp-validation-for="full_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="birth_date" class="control-label"></label>
                <input asp-for="birth_date" class="form-control" type="date" />
                <span asp-validation-for="birth_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Beneficiaries/Delete.cshtml
@model GAP.InsuranceTest.Core.Entities.Beneficiary

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Beneficiary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.full_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.full_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.birth_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.birth_date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Beneficiaries/Details.cshtml
@model GAP.InsuranceTest.Core.Entities.Beneficiary

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Beneficiary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.full_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.full_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.birth_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.birth_date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Beneficiaries/Edit.cshtml
@model GAP.InsuranceTest.Core.Entities.Beneficiary

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Beneficiary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="id_number" class="control-label"></label>
                <input asp-for="id_number" class="form-control" />
                <span asp-validation-for="id_number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="full_name" class="control-label"></label>
                <input asp-for="full_name" class="form-control" />
                <span asp-validation-for="full_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="birth_date" class="control-label"></label>
                <input asp-for="birth_date" class="form-control" />
                <span asp-validation-for="birth_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Beneficiaries/Index.cshtml
@model IEnumerable<GAP.InsuranceTest.Core.Entities.Beneficiary>

@{
    ViewData["Title"] = "Index";
}

<h1>Beneficiarios</h1>

<p>
    <a asp-action="Create" class="btn btn-info">Crear</a>&emsp;
    <a asp-controller="BeneficiaryInsurances" asp-action="Create" class="btn btn-info">Asociar póliza</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Num Identitificación Cliente
            </th>
            <th>
                Nombre Completo
            </th>
            <th>
                Fecha de Nacimiento
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.full_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.birth_date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Modificar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalle</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>